from evoagent.core.llm import LLMClient
from evoagent.skills.evolution import SkillEvolutionEngine
from evoagent.skills.registry import SkillRegistry
from evoagent.skills.runtime import SkillArtifactManager
from evoagent.skills.sandbox import SkillSandbox


class _FakeLLM(LLMClient):
    def generate(self, prompt: str, temperature: float | None = None, profile: str = LLMClient.Profile.STANDARD) -> str:
        _ = prompt, temperature, profile
        return (
            "### name\n"
            "custom_download_skill\n"
            "### description\n"
            "Generic downloader generated by LLM\n"
            "### tags(comma-separated)\n"
            "download,generic,automation\n"
            "### code\n"
            "def execute(input_text: str) -> str:\n"
            "    return 'OK'\n"
            "### tests\n"
            "from skill_impl import execute\n\n"
            "def test_x():\n"
            "    assert execute('a') == 'OK'\n\n"
            "def test_y():\n"
            "    assert execute('b') == 'OK'\n"
        )


def test_generate_github_task_uses_generic_llm_skill_path(tmp_path) -> None:
    engine = SkillEvolutionEngine(
        llm=_FakeLLM(),
        registry=SkillRegistry(tmp_path / "db.sqlite"),
        sandbox=SkillSandbox(),
        artifacts=SkillArtifactManager(tmp_path / "skills"),
    )
    draft = engine.generate_skill("查询一天github上最近热门的十个skills并给你 自己下载", "explicit_failure_marker")
    # Removed hardcoded GitHub draft; result should follow generic LLM output.
    assert draft.name == "custom_download_skill"
    assert "def execute(" in draft.code
    assert "summary.json" not in draft.code
