from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from evoagent.core.llm import LLMClient
from evoagent.skills.registry import SkillRegistry
from evoagent.skills.runtime import SkillArtifactManager


@dataclass
class SkillDraft:
    name: str
    description: str
    tags: list[str]
    code: str
    tests: str


class SkillEvolutionEngine:
    def __init__(
        self,
        llm: LLMClient,
        registry: SkillRegistry,
        sandbox: Any,
        artifacts: SkillArtifactManager,
    ) -> None:
        self.llm = llm
        self.registry = registry
        self.sandbox = sandbox
        self.artifacts = artifacts

    def identify_gap(
        self, quality_score: float, path_length: int, confidence: float
    ) -> bool:
        return quality_score < 0.72 or path_length >= 5 or confidence < 0.55

    def _fallback_draft(self) -> SkillDraft:
        return SkillDraft(
            name="offline_text_compose",
            description="Offline-safe composition skill for fallback mode.",
            tags=["offline", "fallback", "compose"],
            code=(
                "def execute(input_text: str) -> str:\n"
                "    text = input_text.strip()\n"
                "    if not text:\n"
                "        return 'EMPTY'\n"
                "    return f'SUMMARY: {text[:240]}'\n"
            ),
            tests=(
                "from skill_impl import execute\n\n"
                "def test_execute_empty():\n"
                "    assert execute('') == 'EMPTY'\n\n"
                "def test_execute_summary_prefix():\n"
                "    out = execute('hello world')\n"
                "    assert out.startswith('SUMMARY:')\n"
            ),
        )

    def _parse_sections(self, raw: str) -> dict[str, str]:
        sections: dict[str, str] = {}
        current_key: str | None = None
        lines: list[str] = []

        def flush() -> None:
            nonlocal current_key, lines
            if current_key is not None:
                sections[current_key] = "\n".join(lines).strip()
            current_key = None
            lines = []

        for line in raw.splitlines():
            if line.strip().startswith("###"):
                flush()
                header = line.replace("#", "").strip().lower()
                if "name" in header:
                    current_key = "name"
                elif "description" in header:
                    current_key = "description"
                elif "tags" in header:
                    current_key = "tags"
                elif "code" in header:
                    current_key = "code"
                elif "tests" in header:
                    current_key = "tests"
                else:
                    current_key = None
                continue

            if current_key is not None:
                lines.append(line)

        flush()
        return sections

    def _is_valid_draft(self, draft: SkillDraft) -> bool:
        return (
            bool(draft.name.strip())
            and "def execute(" in draft.code
            and "def test_" in draft.tests
            and "from skill_impl import execute" in draft.tests
        )

    def generate_skill(self, task_text: str, failure_reason: str) -> SkillDraft:
        # Removed task-specific hardcoded draft branch; all skill drafts are now
        # generated by the same LLM-driven path to keep evolution generic.

        prompt = (
            "请生成一个 Python Skill 草案，输出格式固定为 5 段，用 ### 分隔：\n"
            "### name\n### description\n### tags(comma-separated)\n### code\n### tests\n"
            f"任务: {task_text}\n"
            f"失败原因: {failure_reason}\n"
            "要求: code 中必须包含可调用函数 execute(input_text: str) -> str；"
            "tests 必须包含至少 2 个 pytest 用例。"
        )
        raw = self.llm.generate(prompt, temperature=0.2)
        if raw.startswith("[Fallback-LLM]"):
            return self._fallback_draft()

        sections = self._parse_sections(raw)
        draft = SkillDraft(
            name=(sections.get("name") or "generated_skill").splitlines()[0].strip(),
            description=sections.get("description") or "Generated skill",
            tags=[
                x.strip()
                for x in (sections.get("tags") or "generated")
                .replace("\n", "")
                .split(",")
                if x.strip()
            ],
            code=sections.get("code") or "",
            tests=sections.get("tests") or "",
        )

        if not self._is_valid_draft(draft):
            return self._fallback_draft()

        return draft

    def validate_and_register(
        self, draft: SkillDraft, version: str | None = None
    ) -> tuple[bool, str]:
        ok, report = self.sandbox.validate(draft.code, draft.tests)
        if not ok:
            return False, f"sandbox failed: {report}"

        resolved_version = version or self.registry.next_version(draft.name)
        status = "candidate"

        self.registry.register(
            name=draft.name,
            version=resolved_version,
            description=draft.description,
            tags=draft.tags,
            status=status,
        )
        self.artifacts.persist(draft, resolved_version, status=status)
        return True, f"registered:{status}"
